apiVersion: v1
kind: Secret
metadata:
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:    
    opendatahub.io/display-name: elyra-pipeline-connection
    opendatahub.io/connection-type: s3
  name: elyra-pipeline-connection
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_ENDPOINT: http://minio-minio.apps.ocp4.example.com
  AWS_S3_BUCKET: elyra-pipeline-bucket
  AWS_SECRET_ACCESS_KEY: minio123
